### ISSUE TITLE
Can not use superquadrics-container

### ISSUE THREAD

**Issue by yoann-fleytoux** [hsp-panda/grasping-benchmarks-panda#23]
Trying to launch the superq_grasp_planner_service get this output:

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.12
 * /superquadric_bench/superq_grasp_planner/config_file: /workspace/catkin...
 * /superquadric_bench/superq_grasp_planner/grasp_planner_service_name: superq_grasp_plan...
 * /superquadric_bench/superq_grasp_planner/grasp_pose_offset: [0.0, 0.0, 0.0]
 * /superquadric_bench/superq_grasp_planner/grasp_publisher_name: candidate_grasp

NODES
  /superquadric_bench/
    superq_grasp_planner (grasping_benchmarks_ros/superq_grasp_planner_service.py)

auto-starting new master
process[master]: started with pid [166]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to bdf6e05e-82b4-11ec-b0c2-c8f75047e806
process[rosout-1]: started with pid [177]
started core service [/rosout]
process[superquadric_bench/superq_grasp_planner-2]: started with pid [180]
RuntimeError: FATAL: module compiled as little endian, but detected different endianness at runtime
Traceback (most recent call last):
  File "/workspace/catkin_ws/src/grasping-benchmarks-panda/grasping_benchmarks_ros/superquadrics_based_ros/superq_grasp_planner_service.py", line 21, in <module>
    from grasping_benchmarks_ros.srv import GraspPlannerCloud
ImportError: cannot import name 'GraspPlannerCloud'
[superquadric_bench/superq_grasp_planner-2] process has died [pid 180, exit code 1, cmd /workspace/catkin_ws/src/grasping-benchmarks-panda/grasping_benchmarks_ros/superquadrics_based_ros/superq_grasp_planner_service.py __name:=superq_grasp_planner __log:=/home/yfleytou/.ros/log/bdf6e05e-82b4-11ec-b0c2-c8f75047e806/superquadric_bench-superq_grasp_planner-2.log].
log file: /home/yfleytou/.ros/log/bdf6e05e-82b4-11ec-b0c2-c8f75047e806/superquadric_bench-superq_grasp_planner-2*.log

GraspPlannerCloud seems to be references as well in the readme but leads to 404 (Grasping Benchmarks Manager section 3), since ./grasping_benchmarks_ros/srv/GraspPlannerCloud.srv does not exists.

**Comment by fbottarel** [comment]
I believe this is relative to a change in service structure I implemented a few months back. I'll address this asap

**Comment by fbottarel** [comment]
Should be fixed by https://github.com/hsp-panda/grasping-benchmarks-panda/commit/54fc84c1030d0901fb070419edcb9ef42480a1c9
